* ChatGPT-Jedi

** About
ChatGPT-Jedi is an Emacs Lisp package that gives you Jedi powers. Yer a space wizard now, Harry.

** Installation
ChatGPT-Jedi isn't on melpa or elpa. You can use use-package to install from github:

#+begin_src elisp
(use-package chatgpt-jedi
  :straight (:host github :repo "CarlQLange/ChatGPT-Jedi.el" :files ("*.el"))
  :init (setq chatgpt-jedi-api-key "your-api-key-here"))
#+end_src

** Usage
There's a bunch of interactive functions, like =chatgpt-jedi-replace-region=, =chatgpt-insert-at-point=, and so on. Some of them even work.

** Requirements
You will need to have an API key from OpenAI’s GPT-3 language model to use this package, and set it as =chatgpt-jedi-api-key=. You can sign up for an API key on the OpenAI website. Depending on how much you use the package, the API cost may vary.

** Credits
This package was developed by Carl Lange with judicious help from ChatGPT.

** License
This package is licensed under the [GNU General Public License v3.0](https://www.gnu.org/licenses/gpl-3.0.en.html).
Important note: code generated by ChatGPT probably has a massive license headache attached to it and may result in RMS eating your dog.
